---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data

```{r}
unzip("./activity.zip")
activity <- read.csv("./activity.csv")
```

## What is mean total number of steps taken per day?

```{r 1.Calculate the total number of steps taken per day, message=FALSE}
library(dplyr)
activity_filtered <- filter(activity, !is.na(steps))
activity_grouped <- group_by(activity_filtered, date)
activity_summary <- summarize(activity_grouped, total_steps=sum(steps))
```

```{r 2.Make a histogram of the total number of steps taken each day}
hist(activity_summary$total_steps)
```

```{r 3.Calculate and report the mean and median of the total number of steps taken per day}
mean(activity_summary$total_steps)
median(activity_summary$total_steps)
```

## What is the average daily activity pattern?

```{r 1.Make a plot of 5-min interval and number of steps taken, averaged across all days, message=FALSE}
library(tidyr)
activity_spreaded         <- spread(activity, date, steps)
activity_spreaded$average <- rowMeans(activity_spreaded[,-1], na.rm=TRUE)
with(activity_spreaded, plot(interval, average, type="l"))
```

```{r 2.Which 5-min interval (on average across all the days) contains the maximum number of steps?}
activity_spreaded$interval[which.max(activity_spreaded$average)]
```

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
